-- Generated from SmartIQ_PDP mapping; verify Verify-flagged names before running
CREATE EXTERNAL TABLE IF NOT EXISTS ${DB}.curated_smartiq_pdp (
  `last_modified_datetime` STRING COMMENT 'src: LastModifiedDatetime | canonical: LastModifiedDatetime',
  `funding_type` STRING COMMENT 'src: FundingType | canonical: FundingType',
  `spending_account` STRING COMMENT 'src: SpendingAccount | canonical: HSAIndicator',
  `network` STRING COMMENT 'src: Network | canonical: Network',
  `ai_typeof_request` STRING COMMENT 'src: AITypeofRequest',
  `ai_select_accand_request_type_ben_changes` STRING COMMENT 'src: AISelectAccandRequestType.BenefitChanges | canonical: BenefitChangeIndicator',
  `ai_select_accand_request_type_explain_group_section_changes` STRING COMMENT 'src: AISelectAccandRequestType.ExplainGroupSectionChanges | canonical: BenefitChangeIndicator',
  `effective_date` STRING COMMENT 'src: EffectiveDate | canonical: EffectiveDate',
  `account_number` STRING COMMENT 'src: AccountNumber | canonical: AccountNumber',
  `account_name` STRING COMMENT 'src: AccountName | canonical: AccountName',
  `ai_legal_group_name` STRING COMMENT 'src: AILegalGroupName | canonical: AccountName',
  `ai_group_name_ifdifferentthan_legal_name` STRING COMMENT 'src: AIGroupName(ifdifferentthanLegalName) | canonical: AccountName',
  `ai_typeof_account` STRING COMMENT 'src: AITypeofAccount',
  `ai_size_contract_count` STRING COMMENT 'src: AISize/ContractCount',
  `grandfathered_status` STRING COMMENT 'src: GrandfatheredStatus | canonical: GrandfatheredStatus',
  `ai_exempt_status` STRING COMMENT 'src: AIExemptionStatus | canonical: ReligiousExemption',
  `ai_muni_county_school_district_stateof_illinois` STRING COMMENT 'src: AIMunicipality/County/SchoolDistrict/StateofIllinois',
  `ai_funding_type` STRING COMMENT 'src: AIFundingType | canonical: FundingType',
  `aihcsc_division` STRING COMMENT 'src: AIHCSCDivision',
  `ai_anniversary_date` STRING COMMENT 'src: AIAnniversaryDate | canonical: AnniversaryDate',
  `ai_performance_guarantee` STRING COMMENT 'src: AIPerformanceGuarantee | canonical: PerformanceGuarantee',
  `ai_collective_bargaining_agreement` STRING COMMENT 'src: AICollectiveBargainingAgreement',
  `ai_cba_term_date` STRING COMMENT 'src: AICbaTermDate',
  `ai_state_benchmark_plan` STRING COMMENT 'src: AIStateBenchmarkPlan | canonical: StateMandates',
  `group_number` STRING COMMENT 'src: GroupNumber | canonical: GroupNumber',
  `ai_groupand_ba_numbers_section_number` STRING COMMENT 'src: AIGroupandBANumbers.SectionNumber',
  `ba_number` STRING COMMENT 'src: BANumber | canonical: BANumber',
  `ai_groupand_ba_numbers_plan_name` STRING COMMENT 'src: AIGroupandBANumbers.PlanName | canonical: PlanName',
  `ai_groupand_ba_numbers_comment` STRING COMMENT 'src: AIGroupandBANumbers.Comment',
  `ai_preparer_full_name` STRING COMMENT 'src: AIPreparerFullName',
  `ai_preparer_phone_number` STRING COMMENT 'src: AIPreparerPhoneNumber',
  `ai_account_manager_full_name` STRING COMMENT 'src: AIAccountManagerFullName | canonical: AccountManager',
  `ai_account_manager_phone_number` STRING COMMENT 'src: AIAccountManagerPhoneNumber | canonical: AccountManager',
  `ai_account_contacts_strategic_account_executive_full_name` STRING COMMENT 'src: AIAccountContactsStrategicAccountExecutive.FullName | canonical: AccountExecutive',
  `ai_account_contacts_strategic_account_executive_phone_number_execution` STRING COMMENT 'src: AIAccountContactsStrategicAccountExecutive.PhoneNumber/Execution | canonical: AccountExecutive',
  `ai_marketing_rep_full_name` STRING COMMENT 'src: AIMarketingRepFullName',
  `ai_marketing_rep_phone_number` STRING COMMENT 'src: AIMarketingRepPhoneNumber',
  `ai_underwriter_full_name` STRING COMMENT 'src: AIUnderwriterFullName',
  `ai_underwriter_phone_number` STRING COMMENT 'src: AIUnderwriterPhoneNumber',
  `ai_account_contacts_group_service_center_phone_number_extension` STRING COMMENT 'src: AIAccountContactsGroupServiceCenter.PhoneNumber/Extension',
  `product` STRING COMMENT 'src: Product | canonical: Product',
  `opdbp_did_group_select` STRING COMMENT 'src: OPDBP.DidGroupSelect | canonical: Product',
  `opdbp_account_remain_on_current_integrated_blue_script_ben` STRING COMMENT 'src: OPDBP.AccountRemainOnCurrentIntegratedBlueScriptBenefits',
  `mcso_med_finder` STRING COMMENT 'src: MCSOMedicationFinder',
  `mcso_flex_access` STRING COMMENT 'src: MCSOFlexAccess',
  `rx_list_drug_list` STRING COMMENT 'src: RXListDrugList | canonical: DrugList',
  `acc_indicate_ded` STRING COMMENT 'src: AccumsIntegrationIndicateDeductible | canonical: PlanYearType',
  `acc_start_date` STRING COMMENT 'src: AccumsIntegrationStartDate | canonical: AccumulatorStartDate',
  `acc_end_date` STRING COMMENT 'src: AccumsIntegrationEndDate | canonical: AccumulatorStartDate',
  `acc_drug_ded` STRING COMMENT 'src: AccumsIntegrationDrugDeductible | canonical: AccumulatorType',
  `acc_drug_oop_max` STRING COMMENT 'src: AccumsiIntegrationDrugOutOfPocketMaximum | canonical: OOPStructure',
  `acc_select_ded_and_oop_sharing_options` STRING COMMENT 'src: AccumsIntegrationSelectDeductibleAndOutofPocketSharingOptions | canonical: AccumulatorType',
  `acc_integration_option` STRING COMMENT 'src: AccumsIntegrationIntegrationOption | canonical: IntegrationOption',
  `acc_select_share_option` STRING COMMENT 'src: AccumsIntegrationSelectShareOption | canonical: AccumulatorType',
  `acc_shared_ded_and_oop_options` STRING COMMENT 'src: AccumsIntegrationSharedDeductibleAndOutofPocketOptions | canonical: AccumulatorType',
  `acc_drug_ded_inn_ind` STRING COMMENT 'src: AccumsIntegrationDrugDeductibleInNetworkIndividual | canonical: Deductible_INN_Individual',
  `acc_drug_ded_inn_fam` STRING COMMENT 'src: AccumsIntegrationDrugDeductibleInNetworkFamily | canonical: Deductible_INN_Family',
  `acc_drug_ded_oon_ind` STRING COMMENT 'src: AccumsIntegrationDrugDeductibleOutofNetworkIndividual | canonical: Deductible_INN_Individual',
  `acc_drug_ded_oon_fam` STRING COMMENT 'src: AccumsIntegrationDrugDeductibleOutofNetworkFamily | canonical: Deductible_INN_Family',
  `acc_drug_oop_max_inn_ind` STRING COMMENT 'src: AccumsIntegrationDrugOutofPocketMaximumInNetworkIndividual | canonical: OOPMax_INN_Individual',
  `acc_drug_oop_max_inn_fam` STRING COMMENT 'src: AccumsIntegrationDrugOutofPocketMaximumInNetworkFamily | canonical: OOPMax_INN_Family',
  `acc_drug_oop_max_oon_ind` STRING COMMENT 'src: AccumsIntegrationDrugOutofPocketMaximumOutofNetworkIndividual | canonical: OOPMax_INN_Individual',
  `acc_drug_oop_max_oon_fam` STRING COMMENT 'src: AccumsIntegrationDrugOutofPocketMaximumOutofNetworkFamily | canonical: OOPMax_INN_Family',
  `acc_select_sep_ded_oop_options` STRING COMMENT 'src: AccumsIntegrationSelectSeparateDeductibleOutofPocketOptions | canonical: AccumulatorType',
  `acc_sep_rx_drug_ded_inn_ind` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugDeductibleInNetworkIndividual | canonical: Deductible_INN_Individual',
  `acc_sep_rx_drug_ded_inn_fam` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugDeductibleInNetworkFamily | canonical: Deductible_INN_Family',
  `acc_sep_rx_drug_ded_oon_ind` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugDeductibleOutofNetworkIndividual | canonical: Deductible_INN_Individual',
  `acc_sep_rx_drug_ded_oon_fam` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugDeductibleOutofNetworkFamily | canonical: Deductible_INN_Family',
  `acc_choose_drugs` STRING COMMENT 'src: AccumsIntegrationChooseDrugs | canonical: DrugAccumulator',
  `acc_sep_rx_drug_oop_max_inn_ind` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugOutofPocketMaximumInNetworkIndividual | canonical: OOPMax_INN_Individual',
  `acc_sep_rx_drug_oop_max_inn_fam` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugOutofPocketMaximumInNetworkFamily | canonical: OOPMax_INN_Family',
  `acc_sep_rx_drug_oop_max_oon_ind` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugOutofPocketMaximumOutofNetworkIndividual | canonical: OOPMax_INN_Individual',
  `acc_sep_rx_drug_oop_max_oon_fam` STRING COMMENT 'src: AccumsIntegrationSeperatePrescriptionDrugOutofPocketMaximumOutofNetworkFamily | canonical: OOPMax_INN_Family',
  `acc_accumulator_load` STRING COMMENT 'src: AccumsIntegrationAccumulatorLoad',
  `acc_choose_sep_ded_accumulation_design` STRING COMMENT 'src: AccumsIntegrationChooseSeperateDeductibleAccumulationDesign | canonical: DeductibleType',
  `acc_choose_sep_oop_accumulation_design` STRING COMMENT 'src: AccumsIntegrationChooseSeperateOutofPocketAccumulationDesign | canonical: OOPStructure',
  `acc_will_sep_drug_ded_apply_to_sep_drug_opx` STRING COMMENT 'src: AccumsIntegrationWillSeperateDrugDeductibleApplyToSeperateDrugOPX | canonical: OOPStructure',
  `acc_other_accums_to_share_with_pharm` STRING COMMENT 'src: AccumsIntregrationOtherAccumsToShareWithPharmacy',
  `acc_is_this_hospital_account` STRING COMMENT 'src: AcumsIntegrationIsThisAHospitalAccount',
  `acc_is_there_tier1_pharm` STRING COMMENT 'src: AccumsIntegrationIsThereATier1Pharmacy',
  `acc_specift_napb_num` STRING COMMENT 'src: AccumsIntegrationSpeciftNAPB#',
  `acc_specify_tier1_pharm_ben_level` STRING COMMENT 'src: AccumsIntegrationSpecifyTier1PharmacyBenefitLevel',
  `acc_accums_to_share` STRING COMMENT 'src: AccumsIntegrationAccumsToShare | canonical: AccumulatorType',
  `acc_how_accums_shared_multi_tiered_medical_network_three_tiers_or_more` STRING COMMENT 'src: AccumsIntegrationHowAccumulatorsSharedMulti-tieredMedicalNetwork(ThreeTiersOrMore) | canonical: AccumulatorType',
  `mac_specify_max_allowable_cost_option` STRING COMMENT 'src: MACSpecifyMaximumAllowableCostOption',
  `mac_specific_max_alowable_cost_option_explain` STRING COMMENT 'src: MACSpecificMaximumAlowableCostOption.Explain',
  `mac_does_mbr_pays_diff_pnlty_apply` STRING COMMENT 'src: MACDoesMemberPaysDifferencePenaltyApply',
  `mac_does_mbr_pays_diff_pnlty_apply_explain` STRING COMMENT 'src: MACDoesMemberPaysDifferencePenaltyApply.Explain',
  `mac_does_mbr_pays_diff_pnlty_waiver_apply` STRING COMMENT 'src: MACDoesMemberPaysDifferencePenaltyWaiverApply',
  `mac_does_mbr_pays_diff_pnlty_brand_medically_necessary` STRING COMMENT 'src: MACDoesMemberPaysDifferencePenaltyBrandMedicallyNecessary',
  `mac_does_mbr_pays_diff_pnlty_waiver_apply_prescriber_fills_out_waiver` STRING COMMENT 'src: MACDoesMemberPaysDifferencePenaltyWaiverApply(PrescriberFillsOutWaiver)',
  `mptd_does_mbr_pays_diff_pnlty_brand_name_drugs` STRING COMMENT 'src: MPTDDoesMemberPaysDifferencePenaltyBrandNameDrugs',
  `mptd_does_mbr_pays_diff_pnlty_brand_name_drugs_explain` STRING COMMENT 'src: MPTDDoesMemberPaysDifferencePenaltyBrandNameDrugs.Explain',
  `mptd_will_mbr_pays_diff_apply_brand_medically_necessary` STRING COMMENT 'src: MPTDWillMemberPaysDifferenceApplyBrandMedicallyNecessary',
  `mptd_does_mbr_pays_diff_pnlty_waiver_apply_prescriber_fills_out_waiver` STRING COMMENT 'src: MPTDDoesMemberPaysDifferencePenaltyWaiverApply(PrescriberFillsOutWaiver)',
  `mptd_does_memeber_pays_diff_pnlty_apply_to_immunosuppressants` STRING COMMENT 'src: MPTDDoesMemeberPaysDifferencePenaltyApplyToImmunosuppressants',
  `day_my_way_mandatory_prog_applies` STRING COMMENT 'src: DayMyWayMandatoryProgramApplies | canonical: DaySupplyRetail',
  `day_my_way_mandatory_prog_select_an_option` STRING COMMENT 'src: DayMyWayMandatoryProgramSelectAnOption | canonical: DaySupplyRetail',
  `rns_select_pharm_retail_network` STRING COMMENT 'src: RNSSelectPharmacyRetailNetwork | canonical: SelectPharmacyRetailNetwork',
  `rns_choose_pref_pharm_retail_network` STRING COMMENT 'src: RNSChoosePreferredPharmacyRetailNetwork | canonical: RetailNetwork',
  `rns_select_addl_brand_member_cost_share` STRING COMMENT 'src: RNSSelectAdditionalBrandMemberCostShare | canonical: AdditionalCostShare',
  `rns_explain` STRING COMMENT 'src: RNSExplain | canonical: RetailNetwork',
  `rns_exclude_day_supply` STRING COMMENT 'src: RNSExcludeDaySupply | canonical: DaySupplyRetail',
  `mds_prsecription_drug_ben_cov` STRING COMMENT 'src: MDSPrsecriptionDrugBenefitCoverage | canonical: DaySupplyRetail',
  `mds_retail_max_day_supply` STRING COMMENT 'src: MDS.RetailMaximumDaySupply | canonical: DaySupplyRetail',
  `mds_retail_max_day_supply_other` STRING COMMENT 'src: MDSRetailMaximumDaySupply.Other | canonical: DaySupplyRetail',
  `mds_retail_max_day_supply_incl_esn` STRING COMMENT 'src: MDSRetailMaximumDaySupply | canonical: DaySupplyRetail',
  `mds_retail_max_day_supply_incl_esn_other` STRING COMMENT 'src: MDSRetailMaximumDaySupplyOther | canonical: DaySupplyRetail',
  `mds_mail_order_max_day_supply` STRING COMMENT 'src: MDSMailOrderMaximumDaySupply | canonical: DaySupplyMail',
  `mds_mail_order_max_day_supply_other` STRING COMMENT 'src: MDSMailOrderMaximumDaySupplyOther | canonical: DaySupplyMail',
  `rx_tiers_pharm_plan_design_tiers` STRING COMMENT 'src: RxTiersPharmacyPlanDesignTiers | canonical: TierStructure',
  `rx_tiers_pharm_plan_design_tiers_other` STRING COMMENT 'src: RXTiersPharmacyPlanDesignTiersOther | canonical: TierStructure',
  `ms_does_copay_coinsurance_apply_after_ded` STRING COMMENT 'src: MSDoesCopay/CoinsuranceApplyAfterDeductible | canonical: CopayType',
  `ms_generic_retail_pharm` STRING COMMENT 'src: MSGenericRetailPharmacy | canonical: GenericTierCost',
  `ms_generic_mail_order` STRING COMMENT 'src: MSGenericMailOrder | canonical: GenericTierCost',
  `ms_generic_esn` STRING COMMENT 'src: MSGenericExtendedSupplyNetwork | canonical: GenericTierCost',
  `ms_generic_spclty` STRING COMMENT 'src: MSGenericSpeciality | canonical: GenericTierCost',
  `ms_non_pref_generic_retail_pharm` STRING COMMENT 'src: MSNonPreferredGenericRetailPharmacy | canonical: NonPreferredCost',
  `ms_non_pref_generic_mail_order` STRING COMMENT 'src: MSNonPreferredGenericMailOrder | canonical: NonPreferredCost',
  `ms_non_pref_generic_esn` STRING COMMENT 'src: MSNonPreferredGenericExtendedSupplyNetwork | canonical: NonPreferredCost',
  `ms_non_pref_generic_spclty` STRING COMMENT 'src: MSNonPreferredGenericSpeciality | canonical: NonPreferredCost',
  `ms_brand_retail_pharm` STRING COMMENT 'src: MSBrandRetailPharmacy | canonical: PreferredBrandCost',
  `ms_brand_mail_order` STRING COMMENT 'src: MSBrandMailOrder | canonical: PreferredBrandCost',
  `ms_brand_esn` STRING COMMENT 'src: MSBrandExtendedSupplyNetwork | canonical: PreferredBrandCost',
  `ms_brand_spclty` STRING COMMENT 'src: MSBrandSpeciality | canonical: PreferredBrandCost',
  `ms_non_pref_brand_retail_pharm` STRING COMMENT 'src: MSNonPreferredBrandRetailPharmacy | canonical: NonPreferredCost',
  `ms_non_pref_brand_mail_order` STRING COMMENT 'src: MSNonPreferredBrandMailOrder | canonical: NonPreferredCost',
  `ms_non_pref_brand_esn` STRING COMMENT 'src: MSNonPreferredBrandExtendedSupplyNetwork | canonical: NonPreferredCost',
  `ms_non_pref_brand_spclty` STRING COMMENT 'src: MSNonPreferredBrandSpeciality | canonical: NonPreferredCost',
  `ms_spclty_retail_pharm` STRING COMMENT 'src: MSSpecialityRetailPharmacy | canonical: SpecialtyTierCost',
  `ms_spclty_mail_order` STRING COMMENT 'src: MSSpecialityMailOrder | canonical: SpecialtyTierCost',
  `ms_spclty_esn` STRING COMMENT 'src: MSSpecialityExtendedSupplyNetwork | canonical: SpecialtyTierCost',
  `ms_spclty_spclty` STRING COMMENT 'src: MSSpecialitySpeciality | canonical: SpecialtyTierCost',
  `ms_non_pref_spclty_retail_pharm` STRING COMMENT 'src: MSNonPreferredSpecialityRetailPharmacy | canonical: NonPreferredSpecialityRetailPharmacy',
  `ms_non_pref_spclty_mail_order` STRING COMMENT 'src: MSNonPreferredSpecialityMailOrder | canonical: NonPreferredSpecialityMailOrder',
  `ms_non_pref_spclty_esn` STRING COMMENT 'src: MSNonPreferredSpecialityExtendedSupplyNetwork | canonical: NonPreferredSpecialityExtendedSupplyNetwork',
  `ms_non_pref_spclty_spclty` STRING COMMENT 'src: MSNonPreferredSpecialitySpeciality | canonical: NonPreferredSpecialitySpeciality',
  `ms_oon_cov` STRING COMMENT 'src: MSOutofNetworkCoverage',
  `md_maintenance_drugs_apply` STRING COMMENT 'src: MDMaintenanceDrugsApply | canonical: MailOrder',
  `md_pref_network` STRING COMMENT 'src: MDPreferredNetwork | canonical: DaySupplyRetail',
  `cp_coupon_accumulator_adjustment` STRING COMMENT 'src: CPCouponAccumulatorAdjustment | canonical: CouponProgram',
  `cp_coupon_maximizer` STRING COMMENT 'src: CPCouponMaximizer | canonical: CouponProgram',
  `sd_spclty_drugs` STRING COMMENT 'src: SDSpecialityDrugs | canonical: SpecialtyCoverage',
  `sd_are_retail_grace_fills_allowed` STRING COMMENT 'src: SDAreRetailGraceFillsAllowed | canonical: FillLimit',
  `sd_choose_one` STRING COMMENT 'src: SDChooseOne | canonical: SpecialtyCoverage',
  `sd_cover_spclty_drugs` STRING COMMENT 'src: SDCoverSpecialityDrugs | canonical: SpecialtyCoverage',
  `sfp_oral_cancer` STRING COMMENT 'src: SFPOralCancer | canonical: SplitFill',
  `sfp_multi_category_split_fill_prog` STRING COMMENT 'src: SFPMultiCategorySplitFillProgram | canonical: SplitFill',
  `aca_does_group_accept_aca_cat` STRING COMMENT 'src: ACADoesGroupAcceptACACategories | canonical: PreventiveDrugCoverage',
  `aca_select_appropriate_options` STRING COMMENT 'src: ACASelectAppropriateOptions | canonical: PreventiveDrugCoverage',
  `aca_are_flu_vaccinations_covered` STRING COMMENT 'src: ACAAreFluVaccinationsCovered | canonical: PreventiveDrugCoverage',
  `aca_specify_cov` STRING COMMENT 'src: ACASpecifyCoverage | canonical: PreventiveDrugCoverage',
  `nspo_smoking_cessation_products` STRING COMMENT 'src: NSPOSmokingCessationProducts | canonical: SmokingCessation',
  `nspo_smoking_cessation_products_ben` STRING COMMENT 'src: NSPOSmokingCessationProductsBenefit | canonical: SmokingCessation',
  `nspo_choose_one_if_addl_non_aca_cov_added` STRING COMMENT 'src: NSPOChooseOne(IfAdditionalNonAcaCoverageAdded)',
  `nspo_sexual_dysfunction_drugs_choose_cov` STRING COMMENT 'src: NSPOSexualDysfunctionDrugs(ChooseCoverage)',
  `nspo_sexual_dysfunction_ben` STRING COMMENT 'src: NSPOSexualDysfunctionBenefit',
  `nspo_obesity_drugs_choose_cov` STRING COMMENT 'src: NSPOObesityDrugs(ChooseCoverage)',
  `nspo_obesity_drugs_ben` STRING COMMENT 'src: NSPOObesityDrugsBenefit',
  `nspo_fertility_drugs_choose_cov` STRING COMMENT 'src: NSPOFertilityDrugs(ChooseCoverage)',
  `nspo_fertility_drugs_ben` STRING COMMENT 'src: NSPOFertilityDrugsBenefit',
  `nspo_fertility_drugs_cov_is_in_vitro_covered_under_medical_plan` STRING COMMENT 'src: NSPOFertilityDrugs(Coverage)IsInVitroCoveredUnderTheMedicalPlan',
  `nspo_max_indicate_type_and_amount_if_applicable` STRING COMMENT 'src: NSPOMaximum(IndicateTypeAndAmount.IfApplicable)',
  `nspo_max_specify_amount_amt` STRING COMMENT 'src: NSPOMaximumSpecifyAmount$',
  `nspo_services_related_to_gender_reassignment_choose_cov` STRING COMMENT 'src: NSPOServicesRelatedToGenderReassignment(ChooseCoverage)',
  `nspo_diabetic_med_and_supplies_choose_cov` STRING COMMENT 'src: NSPODiabeticMedicationAndSupplies(ChooseCoverage)',
  `nspo_insulin_cap_applies` STRING COMMENT 'src: NSPOInsulinCapApplies | canonical: InsulinCap',
  `nspo_heritable_diseases_choose_cov` STRING COMMENT 'src: NSPOHeritableDiseases(ChooseCoverage)',
  `nspo_diabetic_test_strip_down_tiering` STRING COMMENT 'src: NSPODiabeticTestStripDownTiering',
  `nspo_nspo_i_if_obesity_covered` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.IfObesityCovered',
  `nspo_nspo_i_if_weight_loss_agents_traditional_non_glp_1` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.IfWeightLossAgents(Traditional.non-GLP-1)',
  `nspo_nspo_i_if_weight_mgmt_agents_glp_1_plus_combos` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.IfWeightManagementAgents(GLP-1+combos)',
  `nspo_nspo_i_glp_130_daysupply_newto_therapy_ntt` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.GLP-130-daysupplyNewtoTherapy(NTT)',
  `nspo_nspo_i_glp_130_daysupply_newto_therapy_ntt_yes` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.GLP-130-daysupplyNewtoTherapy(NTT)Yes',
  `nspo_nspo_i_if_weight_mgmt_only` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.IfWeightManagementOnly',
  `nspo_nspo_i_if_delayed_effective_date_yes` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.IfDelayedEffectiveDateYES',
  `nspo_nspo_i_glp_130_daysupply_max_all_fill_s` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.GLP-130-daysupplyMaxAllFill(s)',
  `nspo_nspo_i_glp_130_daysupply_max_all_fill_s_yes` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsI.GLP-130-daysupplyMaxAllFill(s)Yes',
  `nspo_nspo_ii_pref_emergency_meds` STRING COMMENT 'src: NSPONon-StandardPharmacyOfferingsII.PreferredEmergencyMedications',
  `nspowps_elects_relig_empl_exempt` STRING COMMENT 'src: NSPOWPSDoesThisAccountElectToProvideAReligiousEmployerExemption | canonical: ReligiousExemption',
  `nspowps_elects_relig_empl_exempt_or_elig_org_accom` STRING COMMENT 'src: NSPOWPSAccountElectToProvideAReligiousEmployerExemptionOrEligibleOrganizationAccommodation | canonical: ReligiousExemption',
  `nspowps_choose_an_applicable_relig_exempt` STRING COMMENT 'src: NSPOWPSChooseAnApplicableReligiousExemption | canonical: ReligiousExemption',
  `nspowps_choose_which_one` STRING COMMENT 'src: NSPOWPSChooseWhichOne | canonical: ReligiousExemption',
  `nspowps_choose_type_of_relig_empl_exempt` STRING COMMENT 'src: NSPOWPSChooseTheTypeOfReligiousEmployerExemption | canonical: ReligiousExemption',
  `nspowps_choose_type_of_elig_org_accom` STRING COMMENT 'src: NSPOWPSChooseTheTypeOfEligibleOrganizationAccomodation | canonical: ReligiousExemption',
  `nspowps_choose_type_of_exempt` STRING COMMENT 'src: NSPOWPSChooseTheTypeOfExemption | canonical: ReligiousExemption',
  `nspowps_entity_desc` STRING COMMENT 'src: NSPOWPSEntityDescription | canonical: ReligiousExemption',
  `nspowps_cover_addl_contras_oral_patches_and_rings` STRING COMMENT 'src: NSPOWPSCoverAdditionalContraceptives(Oral.Patches.AndRings) | canonical: ContraceptiveCoverage',
  `nspowps_contras_cov` STRING COMMENT 'src: NSPOWPSContraceptivesCoverage | canonical: ContraceptiveCoverage',
  `nspo_cover_addl_contra_devices` STRING COMMENT 'src: NSPOCoverAdditionalContraceptiveDevices | canonical: ContraceptiveCoverage',
  `nspowps_addl_contras_cov` STRING COMMENT 'src: NSPOWPSAdditionalContraceptivesCoverage | canonical: ContraceptiveCoverage',
  `nspowps_aca_mandated_contra` STRING COMMENT 'src: NSPOWPSAcaMandatedContraceptive | canonical: ContraceptiveCoverage',
  `nspowps_cover_addl_contras_oral_patches_and_rings_select_one` STRING COMMENT 'src: NSPOWPSCoverAdditionalContraceptives(Oral.Patches.AndRings)SelectOne | canonical: ContraceptiveCoverage',
  `nspowps_cover_addl_contra_devices_select_one` STRING COMMENT 'src: NSPOWPSCoverAdditionalContraceptiveDevicesSelectOne | canonical: ContraceptiveCoverage',
  `nspowps_cover_addl_contras_oral_patches_and_rings_not_listed_in_pharm_cov_list` STRING COMMENT 'src: NSPOWPSCoverAdditionalContraceptives(Oral.Patches.AndRings)NotListedInThePharmacyCoverageList | canonical: ContraceptiveCoverage',
  `nspowps_pharm_cov_list_select_one` STRING COMMENT 'src: NSPOWPSPharmacyCoverageListSelectOne | canonical: ContraceptiveCoverage',
  `nspowps_cover_addl_contra_devices_not_listed_in_pharm_cov_list` STRING COMMENT 'src: NSPOWPSCoverAdditionalContraceptiveDevicesNotListedInThePharmacyCoverageList | canonical: ContraceptiveCoverage',
  `nspowps_addl_contra_devices` STRING COMMENT 'src: NSPOWPSAdditionalContraceptiveDevices | canonical: ContraceptiveCoverage',
  `nspowps_are_rx_contraception_methods_covered` STRING COMMENT 'src: NSPOWPSArePrescriptionContraceptionMethodsCovered | canonical: ContraceptiveCoverage',
  `nspowps_specify_covered_items` STRING COMMENT 'src: NSPOWPSSpecifyCoveredItems | canonical: ContraceptiveCoverage',
  `nspowps_specify_cov_level` STRING COMMENT 'src: NSPOWPSSpecifyCoverageLevel | canonical: ContraceptiveCoverage',
  `nspowps_contras_when_other_drugs_are_covered` STRING COMMENT 'src: NSPOWPSContraceptivesWhenOtherDrugsAreCovered | canonical: ContraceptiveCoverage',
  `nspowps_contra_devices_iuds_diaphragms` STRING COMMENT 'src: NSPOWPSContraceptiveDevices(Iuds.Diaphragms) | canonical: ContraceptiveCoverage',
  `nspowps_contra_depo_provera_im_injectable_cov_on_pharm_plan` STRING COMMENT 'src: NSPOWPSContraceptiveDepoProvera(ImInjectable)CoverageOnPharmacyPlan | canonical: ContraceptiveCoverage',
  `nspo_wps_cover_iu_don_pharm_ben` STRING COMMENT 'src: NSPO.WPS.CoverIUDonPharmacyBenefits | canonical: ContraceptiveCoverage',
  `nspowps_elects_elig_empl_exempt` STRING COMMENT 'src: NSPOWPS.DoesThisAccountElectToProvideEligibleEmployerExemption | canonical: ReligiousExemption',
  `nspowps_elig_empl_exemptionor_elig_org_accom` STRING COMMENT 'src: NSPOWPS.EligibleEmployerExemptionorEligibleOrganizationAccommodation? | canonical: ReligiousExemption',
  `nspowps_elig_exempt` STRING COMMENT 'src: NSPOWPS.EligibleExemption | canonical: ReligiousExemption',
  `nspowps_elig_empl_exempt` STRING COMMENT 'src: NSPOWPS.EligibleEmployerExemption | canonical: ReligiousExemption',
  `nspo_retin_or_pharmacologically_similar_topical_drugs_choose_cov` STRING COMMENT 'src: NSPORetinAOrPharmacologicallySimilarTopicalDrugs(ChooseCoverage)',
  `nspo_does_age_limit_apply` STRING COMMENT 'src: NSPODoesAgeLimitApply',
  `nspo_including_age` STRING COMMENT 'src: NSPOIncludingAge',
  `nspo_non_sedating_antihistamine` STRING COMMENT 'src: NSPONonSedatingAntihistamine | canonical: NSAIDCoverage',
  `nspo_self_injectable_drugs` STRING COMMENT 'src: NSPOSelfInjectableDrugs',
  `are_growth_hormones_covered` STRING COMMENT 'src: AreGrowthHormonesCovered',
  `nspo_compound_drugs` STRING COMMENT 'src: NSPOCompoundDrugs',
  `nspo_add_age_limit_up` STRING COMMENT 'src: NSPOAddAgeLimitUp',
  `nspo_proton_pump_inhibitors_choose_cov` STRING COMMENT 'src: NSPOProtonPumpInhibitors(ChooseCoverage)',
  `nspo_cover_prescribed_over_counter_otc_meds` STRING COMMENT 'src: NSPOCoverPrescribedOverTheCounter(Otc)Medications | canonical: ACA_Otc',
  `nspo_cover_rx_meds_with_otc_equivalents` STRING COMMENT 'src: NSPOCoverPrescriptionMedicationsWithOtcEquivalents | canonical: ACA_Otc',
  `nspo_select_cov` STRING COMMENT 'src: NSPOSelectCoverage',
  `nspo_select_excluded_drug` STRING COMMENT 'src: NSPOSelectExcludedDrug',
  `nspo_cover_omeprazole` STRING COMMENT 'src: NSPOCoverOmeprazole',
  `nspo_cover_otc_equivalent_proton_pump_inhibitors` STRING COMMENT 'src: NSPOCoverOtcEquivalentProtonPumpInhibitors',
  `nspo_nspoii_civica_script_prog` STRING COMMENT 'src: NSPO.NSPOII.CivicaScriptProgram',
  `nspo_civica_script_prog` STRING COMMENT 'src: NSPO.CivicaScriptProgram',
  `nspoil_diabetic_med_and_supplies` STRING COMMENT 'src: NSPOILDiabeticMedicationAndSupplies',
  `nspoil_obesity_drugs` STRING COMMENT 'src: NSPOILObesityDrugs',
  `nspoilaca_mandated_contra` STRING COMMENT 'src: NSPOILACAMandatedContraceptive | canonical: ContraceptiveCoverage',
  `nspoil_proton_pump_inhibitors` STRING COMMENT 'src: NSPOILProtonPumpInhibitors',
  `nspoil_compound_drugs` STRING COMMENT 'src: NSPOILCompoundDrugs',
  `nspoil_non_sedating_antihistamine_nsa_drugs` STRING COMMENT 'src: NSPOILNon-SedatingAntihistamine(NSA)Drugs | canonical: NSAIDCoverage',
  `nspoil_if_covered_is_selected` STRING COMMENT 'src: NSPOILIfCoveredIsSelected',
  `nspoil_other_expl` STRING COMMENT 'src: NSPOILOtherExplanation',
  `nspoil_lancets_coveredat` STRING COMMENT 'src: NSPOILLancetsCoveredat',
  `nspoil_insulin_and_insulin_syringes` STRING COMMENT 'src: NSPOILInsulinAndInsulinSyringes',
  `nspoil_smoking_cessation_products` STRING COMMENT 'src: NSPOILSmokingCessationProducts | canonical: SmokingCessation',
  `nspoil_smoking_cessation_benifits` STRING COMMENT 'src: NSPOILSmokingCessationBenifits | canonical: SmokingCessation',
  `nspoil_specify_copay_values` STRING COMMENT 'src: NSPOILSpecifyCopayValues',
  `nspoil_choose_one` STRING COMMENT 'src: NSPOILChooseOne',
  `nspoilaca_compliant_cov_applies` STRING COMMENT 'src: NSPOILACACompliantCoverageApplies | canonical: ACACompliance',
  `nspoil_typeof_cov` STRING COMMENT 'src: NSPOILTypeofCoverage',
  `nspoil_max` STRING COMMENT 'src: NSPOILMaximum',
  `nspoil_sexual_dysfunction_drugs` STRING COMMENT 'src: NSPOILSexualDysfunctionDrugs',
  `nspoil_fertility_drugs` STRING COMMENT 'src: NSPOILFertilityDrugs',
  `nspoil_check_and_indicate_max_if_applicable` STRING COMMENT 'src: NSPOILCheckAndIndicateMaximumIfApplicable',
  `nspoil_services_related_to_gender_reassignment` STRING COMMENT 'src: NSPOILServicesRelatedToGenderReassignment',
  `nspoil_elects_relig_empl_exempt_or_elig_org_accom` STRING COMMENT 'src: NSPOILAccountElectToProvideAReligiousEmployerExemptionOrEligibleOrganizationccomodation | canonical: ReligiousExemption',
  `nspoil_choose_which_one` STRING COMMENT 'src: NSPOILChooseWhichOne | canonical: ReligiousExemption',
  `nspoil_choose_typeof_relig_empl_exempt` STRING COMMENT 'src: NSPOILChooseTypeofReligiousEmployerExemption | canonical: ReligiousExemption',
  `nspoil_choose_typeof_elig_org_accom` STRING COMMENT 'src: NSPOILChooseTypeofEligibleOrganizationAccomodation | canonical: ReligiousExemption',
  `nspoil_choose_typeof_exempt_accom` STRING COMMENT 'src: NSPOILChooseTypeofExemption/Accomodation | canonical: ReligiousExemption',
  `nspoil_entity_desc` STRING COMMENT 'src: NSPOILEntityDescription | canonical: ReligiousExemption',
  `nspoil_are_rx_contraception_methods_covered` STRING COMMENT 'src: NSPOILArePrescriptionContraceptionMethodsCovered | canonical: ContraceptiveCoverage',
  `nspoil_specify_covered_items` STRING COMMENT 'src: NSPOILSpecifyCoveredItems | canonical: ContraceptiveCoverage',
  `nspoil_specify_cov_level` STRING COMMENT 'src: NSPOILSpecifyCoverageLevel | canonical: ContraceptiveCoverage',
  `nspoil_addl_contras_meds_and_devices` STRING COMMENT 'src: NSPOILAdditionalContraceptivesMedicationsAndDevices | canonical: ContraceptiveCoverage',
  `nspoil_cov` STRING COMMENT 'src: NSPOILCoverage | canonical: ContraceptiveCoverage',
  `nspoil_cov_level` STRING COMMENT 'src: NSPOILCoverageLevel | canonical: ContraceptiveCoverage',
  `nspoil_covered_contra_types` STRING COMMENT 'src: NSPOILCoveredContraceptiveTypes | canonical: ContraceptiveCoverage',
  `nspoil_cov_level_options` STRING COMMENT 'src: NSPOILCoverageLevelOptions | canonical: ContraceptiveCoverage',
  `nspoil_cover_addl_contras` STRING COMMENT 'src: NSPOILCoverAdditionalContraceptives | canonical: ContraceptiveCoverage',
  `nspoil_if_yes_selected` STRING COMMENT 'src: NSPOILIfYesSelected | canonical: ContraceptiveCoverage',
  `nspoil_cover_addl_contra_devices` STRING COMMENT 'src: NSPOILCoverAdditionalContraceptiveDevices | canonical: ContraceptiveCoverage',
  `nspoil_retin_or_pharmacologically_similar_trop_drugs` STRING COMMENT 'src: NSPOILRetinAOrPharmacologicallySimilarTropDrugs',
  `nspoil_does_age_limit_apply` STRING COMMENT 'src: NSPOILDoesAgeLimitApply',
  `nspoil_upto_and_including_age` STRING COMMENT 'src: NSPOILUptoAndIncludingAge',
  `nspoil_self_injectable_drugs` STRING COMMENT 'src: NSPOILSelf-InjectableDrugs',
  `nspoil_are_growth_hormones_covered` STRING COMMENT 'src: NSPOILAreGrowthHormonesCovered',
  `nspoil_cover_rx_meds_with_otc_equivalents` STRING COMMENT 'src: NSPOILCoverPrescriptionMedicationsWithOTCEquivalents | canonical: ACA_Otc',
  `nspoil_cover_otc_equivalent_proton_pump_inhibitors` STRING COMMENT 'src: NSPOILCoverOTCEquivalentProtonPumpInhibitors',
  `nspoil_cover_addl_contras_meds_and_devices` STRING COMMENT 'src: NSPOILCoverAdditionalContraceptivesMedicationsAndDevices | canonical: ContraceptiveCoverage',
  `nspoil_if_obesity_covered` STRING COMMENT 'src: NSPOIL.IfObesityCovered',
  `nspoil_if_weight_loss_agents_traditional_non_glp_1` STRING COMMENT 'src: NSPOIL.IfWeightLossAgents(Traditional.non-GLP-1)',
  `nspoil_if_weight_mgmt_agents_glp_1_plus_combos` STRING COMMENT 'src: NSPOIL.IfWeightManagementAgents(GLP-1+combos)',
  `nspoil_glp_1_30_day_supply_ntt` STRING COMMENT 'src: NSPOIL.GLP-1_30-daySupplyNTT',
  `nspoil_glp_1_30_day_supply_ntt_yes` STRING COMMENT 'src: NSPOIL.GLP-1_30-daySupplyNTTYes',
  `nspoil_if_weight_mgmt_only` STRING COMMENT 'src: NSPOIL.IfWeightManagementOnly',
  `nspoil_if_delayed_effective_date_yes` STRING COMMENT 'src: NSPOIL.IfDelayedEffectiveDateYES',
  `nspoil_glp_1_30daysupply_max_all_fill_s` STRING COMMENT 'src: NSPOIL.GLP-1_30daysupplyMaxAllFill(s)',
  `nspoil_glp_1_30daysupply_max_all_fill_s_yes` STRING COMMENT 'src: NSPOIL.GLP-1_30daysupplyMaxAllFill(s)Yes',
  `nspoil_epi_pen_cap_choose_cov` STRING COMMENT 'src: NSPOIL.Epi-PenCap(ChooseCoverage)',
  `nspoil_insulin_cap_choose_cov` STRING COMMENT 'src: NSPOIL.InsulinCap(ChooseCoverage) | canonical: InsulinCap',
  `nspoil_elects_elig_empl_exempt_or_elig_org_accom` STRING COMMENT 'src: NSPOIL.DOesThisAccountElectToProvideEligibleEmployerExemptionOrEligibleOrganizationAccommodation | canonical: ReligiousExemption',
  `nspoil_choose_type_of_elig_empl_exempt` STRING COMMENT 'src: NSPOIL.ChooseTypeOfEligibleEmployerExemption | canonical: ReligiousExemption',
  `nspoil_cover_iu_don_pharm_ben` STRING COMMENT 'src: NSPOIL.CoverIUDonPharmacyBenefits | canonical: ContraceptiveCoverage',
  `nspoil_dms_if_covered_selected` STRING COMMENT 'src: NSPOIL.DMSIfCoveredSelected',
  `nspoil_dms_other_expl` STRING COMMENT 'src: NSPOIL.DMSOtherExplanation',
  `nspoil_iis_if_covered_selected` STRING COMMENT 'src: NSPOIL.IISIfCoveredSelected',
  `nspoil_iis_other_expl` STRING COMMENT 'src: NSPOIL.IISOtherExplanation',
  `nspoil_tc_other_expl` STRING COMMENT 'src: NSPOIL.TCOtherExplanation',
  `nspoil_max_other_expl` STRING COMMENT 'src: NSPOIL.MaxOtherExplanation',
  `nspoil_fd_other_expl` STRING COMMENT 'src: NSPOIL.FDOtherExplanation',
  `nspoil_add_in_contra_if_yes_selected` STRING COMMENT 'src: NSPOIL.AddInContraIfYesSelected | canonical: ContraceptiveCoverage',
  `nspoil_iud_if_yes_selected` STRING COMMENT 'src: NSPOIL.IUDIfYesSelected | canonical: ContraceptiveCoverage',
  `nspoil_pref_emergency_meds` STRING COMMENT 'src: NSPOIL.PreferredEmergencyMedications',
  `nspoil_vision_enhancement_products` STRING COMMENT 'src: NSPOILVisionEnhancementProducts',
  `nspoil_keep_well` STRING COMMENT 'src: NSPOIL.KeepWell',
  `nspoil_network_configuration` STRING COMMENT 'src: NSPOIL.NetworkConfiguration | canonical: RetailNetwork',
  `ump_choose_which_um_option_is_selected` STRING COMMENT 'src: UMPChooseWhichUmOptionIsSelected | canonical: UMOption',
  `ump_should_um_fastpath_prog_apply` STRING COMMENT 'src: UMPShouldUmFastpathProgramApply | canonical: UMOption',
  `ump_should_new_to_market_prog_apply` STRING COMMENT 'src: UMPShouldNewToMarketProgramApply | canonical: UMOption',
  `ump_non_spclty_prior_auth_prog_apply` STRING COMMENT 'src: UMPNonSpecialtyPriorAuthorizationProgramApply | canonical: PriorAuthorization',
  `ump_non_spclty_prior_auth_select_all` STRING COMMENT 'src: UMPNonSpecialtyPriorAuthorizationSelectAllThatApply | canonical: PriorAuthorization',
  `ump_non_spclty_prior_auth_addl_prog_s` STRING COMMENT 'src: UMPNonSpecialtyPriorAuthorizationAdditionalProgram(S) | canonical: CustomPrograms',
  `ump_spclty_prior_auth_prog_apply` STRING COMMENT 'src: UMPSpecialityPriorAuthorizationProgramApply | canonical: PriorAuthorization',
  `ump_spclty_prior_auth_select_all` STRING COMMENT 'src: UMPSpecialityPriorAuthorizationSelectAllThatApply | canonical: PriorAuthorization',
  `ump_spclty_prior_auth_addl_prog_s` STRING COMMENT 'src: UMPSpecialityPriorAuthorizationAdditionalProgram(S) | canonical: CustomPrograms',
  `ump_non_standard_prior_auth_prog_apply` STRING COMMENT 'src: UMPNonStandardPriorAuthorizationProgramApply | canonical: PriorAuthorization',
  `ump_non_standard_prior_auth_select_all` STRING COMMENT 'src: UMPNonStandardPriorAuthorizationSelectAllThatApply | canonical: PriorAuthorization',
  `ump_non_standard_prior_auth_addl_prog_s` STRING COMMENT 'src: UMPNonStandardPriorAuthorizationAdditionalProgram(S) | canonical: CustomPrograms',
  `ump_non_spclty_step_therapy_therapy_apply` STRING COMMENT 'src: UMPNonSpecialtyStepTherapyTherapyApply | canonical: StepTherapy',
  `ump_non_spclty_step_therapy_select_all` STRING COMMENT 'src: UMPNonSpecialtyStepTherapySelectAllThatApply | canonical: StepTherapy',
  `ump_non_spclty_step_therapy_addl_prog_s` STRING COMMENT 'src: UMPNonSpecialtyStepTherapyAdditionalProgram(S) | canonical: CustomPrograms',
  `ump_spclty_step_therapy_therapy_apply` STRING COMMENT 'src: UMPSpecialtyStepTherapyTherapyApply | canonical: StepTherapy',
  `ump_spclty_step_therapy_select_all` STRING COMMENT 'src: UMPSpecialtyStepTherapySelectAllThatApply | canonical: StepTherapy',
  `ump_spclty_step_therapy_addl_prog_s` STRING COMMENT 'src: UMPSpecialtyStepTherapyAdditionalProgram(S) | canonical: CustomPrograms',
  `ump_non_standard_step_therapy_therapy_apply` STRING COMMENT 'src: UMPNonStandardStepTherapyTherapyApply | canonical: StepTherapy',
  `ump_non_standard_step_therapy_select_all` STRING COMMENT 'src: UMPNonStandardStepTherapySelectAllThatApply | canonical: StepTherapy',
  `ump_non_standard_step_therapy_addl_prog_s` STRING COMMENT 'src: UMPNonStandardStepTherapyAdditionalProgram(S) | canonical: CustomPrograms',
  `ump_should_prog_apply` STRING COMMENT 'src: UMPShouldProgramApply | canonical: UMOption',
  `ppbcr_select_pricing_prog_bundle` STRING COMMENT 'src: PPBCRSelectPricingProgramBundle',
  `ppbcr_pharm_commission_rates_apply` STRING COMMENT 'src: PPBCRPharmacyCommissionRatesApply',
  `ppbcr_specify_amount_amt` STRING COMMENT 'src: PPBCRSpecifyAmount$',
  `ppbcr_select_rate_type` STRING COMMENT 'src: PPBCRSelectRateType',
  `rx_run_way_transition_ben` STRING COMMENT 'src: RXRunWay(TransitionBenefits)',
  `nacapdp_does_non_aca_prev_drug_prog_apply` STRING COMMENT 'src: NACAPDPDoesTheNonAcaPreventiveDrugProgramApply | canonical: PreventiveDrugCoverage',
  `nacapdp_choose_which_non_aca_prev_prog_option_is_selected` STRING COMMENT 'src: NACAPDPChooseWhichNonAcaPreventiveProgramOptionIsSelected | canonical: PreventiveDrugCoverage',
  `nacapdp_non_aca_prev_drug_cat` STRING COMMENT 'src: NACAPDPNonAcaPreventiveDrugCategories | canonical: PreventiveDrugCoverage',
  `nacapdp_prev_cat_waive_copay_coinsurance` STRING COMMENT 'src: NACAPDPPreventiveCategoriesWaiveCopay/Coinsurance | canonical: PreventiveDrugCoverage',
  `nacapdp_specify_copay_coins_details` STRING COMMENT 'src: NACAPDPSpecifyCopay/CoinsDetails | canonical: PreventiveDrugCoverage',
  `nacapdp_standard_cat` STRING COMMENT 'src: NACAPDPStandardCategories | canonical: PreventiveDrugCoverage',
  `nacapdp_optional_cat` STRING COMMENT 'src: NACAPDPOptionalCategories | canonical: PreventiveDrugCoverage',
  `nacapdp_custom_cat` STRING COMMENT 'src: NACAPDPCustomCategories | canonical: PreventiveDrugCoverage',
  `pdm_rx_drug_max` STRING COMMENT 'src: PDMPrescriptionDrugMaximum',
  `pdm_rx_drug_max_other` STRING COMMENT 'src: PDMPrescriptionDrugMaximumOther',
  `pdm_annual_max_ind_annual_max` STRING COMMENT 'src: PDMAnnualMaximum.IndividualAnnualMaximum',
  `pdm_annual_max_fam_annual_max` STRING COMMENT 'src: PDMAnnualMaximum.FamilyAnnualMaximum',
  `pdm_lifetime_max_ind_lifetime_max` STRING COMMENT 'src: PDMLifetimeMaximum.IndividualLifetimeMaximum',
  `pdm_liftime_max_fam_lifetime_max` STRING COMMENT 'src: PDMLiftimeMaximum.FamilyLifetimeMaximum',
  `pdm_rx_drug_max_appliesto` STRING COMMENT 'src: PDMPrescriptionDrugMaximumAppliesto',
  `pdm_rx_drug_max_appliesto_other` STRING COMMENT 'src: PDMPrescriptionDrugMaximumAppliestoOther',
  `overrides_lost_or_stolen_med_overrides` STRING COMMENT 'src: Overrides.LostOrStolenMedicationOverrides | canonical: OverrideFlags',
  `overrides_vacation_override` STRING COMMENT 'src: Overrides.VacationOverride | canonical: OverrideFlags',
  `mcso_flex_access_qualified_hdhp` STRING COMMENT 'src: MCSOFlexAccessQualifiedHDHP | canonical: HSAIndicator',
  `nspo_vision_enhancement_products` STRING COMMENT 'src: NSPOVisionEnhancementProducts',
  `gem_case_id` STRING COMMENT 'src: Gem_Case_ID',
  `current_date_time` STRING COMMENT 'src: CurrentDateTime',
  `ai_acc_info_is_group_muni_county_school_district_stateof_texas` STRING COMMENT 'src: AIAccInfo.IsGroupMunicipality/County/SchoolDistrict/StateofTexas',
  `mop_mail_order_pharm` STRING COMMENT 'src: MOP.MailOrderPharmacy | canonical: MailOrder',
  `ms_spclty_cost_share_multiplier` STRING COMMENT 'src: MSSpecialtyCostShareMultiplier | canonical: SpecialtyTierCost',
  `ai_acc_info_retiree_only_plan` STRING COMMENT 'src: AI.AccInfo.RetireeOnlyPlan',
  `ai_salesforce_ge_ms_case_number` STRING COMMENT 'src: AI.SalesforceGEMsCaseNumber',
  `sd_advocate_plus_pharm_match` STRING COMMENT 'src: SD.Advocate+PharmacyMatch',
  `ai_acc_info_non_erisa_designation` STRING COMMENT 'src: AI.AccInfo.NonErisaDesignation',
  `nspoi_keep_well` STRING COMMENT 'src: NSPOI.KeepWell',
  `nspoi_network_configuration` STRING COMMENT 'src: NSPOI.NetworkConfiguration | canonical: RetailNetwork',
  `src_form_guid` STRING COMMENT 'lineage/dedup key (recommended - confirm)',
  `curated_load_ts` STRING COMMENT 'curated load timestamp'
)
PARTITIONED BY (`load_dt` STRING)
STORED AS PARQUET
LOCATION '${LOCATION}/curated_smartiq_pdp';